/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import static gui.Login.log1;
import gui.output.SelectError;
import gui.output.Success;
import java.awt.Color;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;

/**
 *
 * @author user
 */
public class Restore extends javax.swing.JFrame {

    /**
     * Creates new form Restore
     */
    public Restore() {
        initComponents();
    }
     String location=null;
    String filename;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        addYield_CloseBtn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buyer_name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buyer_insert = new javax.swing.JButton();
        buyerUpdate_insert = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        addYield_CloseBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addYield_CloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancel.png"))); // NOI18N
        addYield_CloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addYield_CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addYield_CloseBtnMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/leaf.png"))); // NOI18N
        jLabel4.setText(" A G R I ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addYield_CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
            .addComponent(addYield_CloseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Cloud hosting.gif"))); // NOI18N
        jLabel1.setText(" ");

        buyer_name.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        buyer_name.setForeground(new java.awt.Color(51, 0, 51));
        buyer_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        buyer_name.setOpaque(false);
        buyer_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyer_nameActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setText("SELECTED PATH");

        buyer_insert.setBackground(new java.awt.Color(255, 246, 207));
        buyer_insert.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        buyer_insert.setText("CHOOSE BACKUP");
        buyer_insert.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 102, 0)));
        buyer_insert.setContentAreaFilled(false);
        buyer_insert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buyer_insert.setFocusPainted(false);
        buyer_insert.setOpaque(true);
        buyer_insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buyer_insertMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buyer_insertMouseExited(evt);
            }
        });
        buyer_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyer_insertActionPerformed(evt);
            }
        });

        buyerUpdate_insert.setBackground(new java.awt.Color(0, 255, 153));
        buyerUpdate_insert.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        buyerUpdate_insert.setText("RESTORE");
        buyerUpdate_insert.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 102, 0)));
        buyerUpdate_insert.setContentAreaFilled(false);
        buyerUpdate_insert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buyerUpdate_insert.setFocusPainted(false);
        buyerUpdate_insert.setOpaque(true);
        buyerUpdate_insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buyerUpdate_insertMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buyerUpdate_insertMouseExited(evt);
            }
        });
        buyerUpdate_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyerUpdate_insertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buyer_name)
                        .addComponent(buyer_insert, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
                    .addComponent(buyerUpdate_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buyer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buyer_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(buyerUpdate_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addYield_CloseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addYield_CloseBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_addYield_CloseBtnMouseClicked

    private void buyer_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyer_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyer_nameActionPerformed

    private void buyer_insertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyer_insertMouseEntered
        buyer_insert.setBackground(new Color(193, 153, 111));
        buyer_insert.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_buyer_insertMouseEntered

    private void buyer_insertMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyer_insertMouseExited
        buyer_insert.setBackground(new Color(255, 246, 207));
        buyer_insert.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_buyer_insertMouseExited

    private void buyer_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyer_insertActionPerformed
        JFileChooser path =new JFileChooser();
        path.showOpenDialog(this);
        String date=new SimpleDateFormat("yyyy-MM-dd").format(new Date());
        try {
            File f=path.getSelectedFile();
            location=f.getAbsolutePath();
            location=location.replace("\\","/");
                filename=location + "_"+ date +".sql";
                buyer_name.setText(filename);
            } catch (Exception e) {
                log1.warning(e.toString());
            }

    }//GEN-LAST:event_buyer_insertActionPerformed

    private void buyerUpdate_insertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyerUpdate_insertMouseEntered
        buyerUpdate_insert.setBackground(new Color(0, 255, 153));
        buyerUpdate_insert.setForeground(new Color(0,0, 0));
    }//GEN-LAST:event_buyerUpdate_insertMouseEntered

    private void buyerUpdate_insertMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyerUpdate_insertMouseExited
        buyerUpdate_insert.setBackground(new Color(42, 245, 164));
        buyerUpdate_insert.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_buyerUpdate_insertMouseExited

    private void buyerUpdate_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyerUpdate_insertActionPerformed
        String user="root";
        String pass="";
        String[] restoreCmd=new String[]{"C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe","--user="+user,"--password="+pass,"-e","source "+filename};
        Process process;
        try {
            process=Runtime.getRuntime().exec(restoreCmd);
            int proCom=process.waitFor();
            
            if(proCom==0){
                 Success success=new Success();
                success.setVisible(true);
            }else{
                SelectError categoryExists=new SelectError();
            categoryExists.setText("Couldn't Restore");
            categoryExists.setVisible(true);
            }
        } catch (Exception e) {
            log1.warning(e.toString());
        }
    }//GEN-LAST:event_buyerUpdate_insertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addYield_CloseBtn;
    private javax.swing.JButton buyerUpdate_insert;
    private javax.swing.JButton buyer_insert;
    private javax.swing.JTextField buyer_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
